{% set name = "languagetool-code-comments" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dustinblackman/languagetool-code-comments
  git_rev: v{{ version }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - languagetool-code-comments --help

about:
  home: https://github.com/dustinblackman/languagetool-code-comments
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: LanguageTool API in Rust
  dev_url: https://github.com/dustinblackman/languagetool-code-comments

extra:
  recipe-maintainers:
    - danielnachun
