context:
  version: 0.6.3

package:
  name: languagetool-code-comments
  version: ${{ version }}

source:
  - git: https://github.com/dustinblackman/languagetool-code-comments
    tag: v${{ version }}
    target_directory: src
  - url: https://github.com/dustinblackman/languagetool-code-comments/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 5062ce687beb2f4dc676c9b6849a533b65585a540b77527481f472cbfd0506c1

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
    - libgit2
  host:
    - openssl

tests:
  - script:
      - languagetool-code-comments --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: LanguageTool API in Rust
  homepage: https://github.com/dustinblackman/languagetool-code-comments
  repository: https://github.com/dustinblackman/languagetool-code-comments

extra:
  recipe-maintainers:
    - danielnachun
